version: '3.7'

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    networks:
      backbone:
        ipv4_address: 10.0.16.2
    volumes:
      - /lib/modules:/lib/modules
      - ./config:/config
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - TZ=Asia/Tokyo
    networks:
      backbone:
        ipv4_address: 10.0.16.3
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

networks:
  backbone:
    name: backbone
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.16.0/24
